const events = [
  "Hong Kong protests",
  "Bushfires",
  "Drone strikes",
  "Trump (impeachment)",
  "Brexit",
  "COVID-19",
  "Stock market",
  "Italy quarantine",
  "Ebola outbreak",
  "USA Leaving WHO",
  "Economic depression",
  "Oil prices",
  "Cyclones",
  "Racism",
  "Police brutality",
  "Earthquakes",
  "Floods",
  "Beirut explosion",
  "Harvey Weinstein",
  "Death of Kobe Bryant",
  "Death of Chadwick Boseman",
  "West coast wildfires",
  "Armenia-Azerbaijan conflicts",
  "Terrorism",
  "Second wave",
  "Belarus protests",
  "Global warming",
  "Social media/Facebook",
  "Anti-maskers",
].map((v) => v.toUpperCase());

const fuckings = [
  "Trump",
  "Totalitarism",
  "Fascism",
  "Climate change",
  "Corporations",
  "War",
  "Famine",
  "Pestilence",
].map((v) => v.toUpperCase());

export { events, fuckings };
